/*
 * FAI Cart API
 * This API is part of Fujitsu's Cloud Lab Demo
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pavan.vadarevu@fujitsu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fujitsu.cloudlab.cart.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * CartSearchCriteria
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-04T20:28:40.576-04:00")
public class CartSearchCriteria {
  @JsonProperty("cartId")
  private UUID cartId = null;

  @JsonProperty("offerId")
  private UUID offerId = null;

  @JsonProperty("offerExpirationDate")
  private String offerExpirationDate = null;

  public CartSearchCriteria cartId(UUID cartId) {
    this.cartId = cartId;
    return this;
  }

   /**
   * Unique id generated for each cart.
   * @return cartId
  **/
  @ApiModelProperty(value = "Unique id generated for each cart.")
  public UUID getCartId() {
    return cartId;
  }

  public void setCartId(UUID cartId) {
    this.cartId = cartId;
  }

  public CartSearchCriteria offerId(UUID offerId) {
    this.offerId = offerId;
    return this;
  }

   /**
   * Get offerId
   * @return offerId
  **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", value = "")
  public UUID getOfferId() {
    return offerId;
  }

  public void setOfferId(UUID offerId) {
    this.offerId = offerId;
  }

  public CartSearchCriteria offerExpirationDate(String offerExpirationDate) {
    this.offerExpirationDate = offerExpirationDate;
    return this;
  }

   /**
   * Get offerExpirationDate
   * @return offerExpirationDate
  **/
  @ApiModelProperty(value = "")
  public String getOfferExpirationDate() {
    return offerExpirationDate;
  }

  public void setOfferExpirationDate(String offerExpirationDate) {
    this.offerExpirationDate = offerExpirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartSearchCriteria cartSearchCriteria = (CartSearchCriteria) o;
    return Objects.equals(this.cartId, cartSearchCriteria.cartId) &&
        Objects.equals(this.offerId, cartSearchCriteria.offerId) &&
        Objects.equals(this.offerExpirationDate, cartSearchCriteria.offerExpirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cartId, offerId, offerExpirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartSearchCriteria {\n");
    
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    offerExpirationDate: ").append(toIndentedString(offerExpirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

