/*
 * FAI Cart API
 * This API is part of Fujitsu's Cloud Lab Demo
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pavan.vadarevu@fujitsu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fujitsu.cloudlab.cart.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fujitsu.cloudlab.cart.model.Customer;
import com.fujitsu.cloudlab.cart.model.Price;
import com.fujitsu.cloudlab.cart.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * Offer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-04T20:28:40.576-04:00")
public class Offer {
  @JsonProperty("offerId")
  private UUID offerId = null;

  @JsonProperty("offerType")
  private String offerType = null;

  @JsonProperty("offerPrice")
  private Price offerPrice = null;

  @JsonProperty("paymentTimeLimitUtcTs")
  private String paymentTimeLimitUtcTs = null;

  @JsonProperty("offerCreationDate")
  private String offerCreationDate = null;

  @JsonProperty("offerExpirationDate")
  private String offerExpirationDate = null;

  @JsonProperty("product")
  private Product product = null;

  @JsonProperty("customers")
  private Customer customers = null;

  public Offer offerId(UUID offerId) {
    this.offerId = offerId;
    return this;
  }

   /**
   * Get offerId
   * @return offerId
  **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", required = true, value = "")
  public UUID getOfferId() {
    return offerId;
  }

  public void setOfferId(UUID offerId) {
    this.offerId = offerId;
  }

  public Offer offerType(String offerType) {
    this.offerType = offerType;
    return this;
  }

   /**
   * Get offerType
   * @return offerType
  **/
  @ApiModelProperty(example = "BlackFridaySpl2020", required = true, value = "")
  public String getOfferType() {
    return offerType;
  }

  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  public Offer offerPrice(Price offerPrice) {
    this.offerPrice = offerPrice;
    return this;
  }

   /**
   * Get offerPrice
   * @return offerPrice
  **/
  @ApiModelProperty(value = "")
  public Price getOfferPrice() {
    return offerPrice;
  }

  public void setOfferPrice(Price offerPrice) {
    this.offerPrice = offerPrice;
  }

  public Offer paymentTimeLimitUtcTs(String paymentTimeLimitUtcTs) {
    this.paymentTimeLimitUtcTs = paymentTimeLimitUtcTs;
    return this;
  }

   /**
   * Payment Time Limit UTC Timestamp represents the date by which a commitment to pay must be made for the confirmed items in an offer. _ _Example:__2018-04-17T20:02:28+0500__(ISO 8601 format YYYY-MM-DDThh:mm s+|-hhmm)
   * @return paymentTimeLimitUtcTs
  **/
  @ApiModelProperty(value = "Payment Time Limit UTC Timestamp represents the date by which a commitment to pay must be made for the confirmed items in an offer. _ _Example:__2018-04-17T20:02:28+0500__(ISO 8601 format YYYY-MM-DDThh:mm s+|-hhmm)")
  public String getPaymentTimeLimitUtcTs() {
    return paymentTimeLimitUtcTs;
  }

  public void setPaymentTimeLimitUtcTs(String paymentTimeLimitUtcTs) {
    this.paymentTimeLimitUtcTs = paymentTimeLimitUtcTs;
  }

  public Offer offerCreationDate(String offerCreationDate) {
    this.offerCreationDate = offerCreationDate;
    return this;
  }

   /**
   * Get offerCreationDate
   * @return offerCreationDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOfferCreationDate() {
    return offerCreationDate;
  }

  public void setOfferCreationDate(String offerCreationDate) {
    this.offerCreationDate = offerCreationDate;
  }

  public Offer offerExpirationDate(String offerExpirationDate) {
    this.offerExpirationDate = offerExpirationDate;
    return this;
  }

   /**
   * Get offerExpirationDate
   * @return offerExpirationDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOfferExpirationDate() {
    return offerExpirationDate;
  }

  public void setOfferExpirationDate(String offerExpirationDate) {
    this.offerExpirationDate = offerExpirationDate;
  }

  public Offer product(Product product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(required = true, value = "")
  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Offer customers(Customer customers) {
    this.customers = customers;
    return this;
  }

   /**
   * Get customers
   * @return customers
  **/
  @ApiModelProperty(value = "")
  public Customer getCustomers() {
    return customers;
  }

  public void setCustomers(Customer customers) {
    this.customers = customers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Offer offer = (Offer) o;
    return Objects.equals(this.offerId, offer.offerId) &&
        Objects.equals(this.offerType, offer.offerType) &&
        Objects.equals(this.offerPrice, offer.offerPrice) &&
        Objects.equals(this.paymentTimeLimitUtcTs, offer.paymentTimeLimitUtcTs) &&
        Objects.equals(this.offerCreationDate, offer.offerCreationDate) &&
        Objects.equals(this.offerExpirationDate, offer.offerExpirationDate) &&
        Objects.equals(this.product, offer.product) &&
        Objects.equals(this.customers, offer.customers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerId, offerType, offerPrice, paymentTimeLimitUtcTs, offerCreationDate, offerExpirationDate, product, customers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Offer {\n");
    
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    offerType: ").append(toIndentedString(offerType)).append("\n");
    sb.append("    offerPrice: ").append(toIndentedString(offerPrice)).append("\n");
    sb.append("    paymentTimeLimitUtcTs: ").append(toIndentedString(paymentTimeLimitUtcTs)).append("\n");
    sb.append("    offerCreationDate: ").append(toIndentedString(offerCreationDate)).append("\n");
    sb.append("    offerExpirationDate: ").append(toIndentedString(offerExpirationDate)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    customers: ").append(toIndentedString(customers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

